### PR TITLE
Replace net::http with httprb to optimize post requests

### PR DESCRIPTION
**Pull request by linyaoli**
As the client sends massive amount of post requests to agent, I'd like to use https://github.com/httprb/http to replace Ruby's standard `Net::HTTP`, which could, in theory, improve the client's performance and reduce the time cost.

A nice article about it:
https://twin.github.io/httprb-is-great/

Please have a look. Thanks in advance.

### CODE REVIEW

**Comment by guizmaii** [comment]
Is there any tangible benchmarks that can show the benefits to move to http.rb please ? Can you write some ?

**Comment by linyaoli** [comment]
Hi @guizmaii, I haven't done homemade benchmarking yet, but there are a bunch of testings we can refer to:
1. Performance on speed
https://github.com/httprb/http#another-ruby-http-library-why-should-i-care 
2. Memory efficiency
https://twin.github.io/httprb-is-great/#memory-usage

I think these could clarify my point.

**Comment by linyaoli** [comment]
stale

**Comment by delner** [comment]
@linyaoli we recently overhauled our transport layer in #628 to allow for a variety of different adapters to be used to submit traces. With these changes, it would be possible to develop a custom adapter that implements HTTP.rb as a replacement for `Net::HTTP`.

Once implemented, activating it could look like:

```
Datadog.configure do |c|
  c.tracer transport_options: proc { |t| t.adapter :httprb }
end
```

For more details how you could implement such an adapter, check out the [development guide](https://github.com/DataDog/dd-trace-rb/blob/master/docs/DevelopmentGuide.md) or [some other adapters](https://github.com/DataDog/dd-trace-rb/tree/master/lib/ddtrace/transport/http/adapters) that have been implemented in a similar fashion.

If this is sufficient to revive this PR as a new HTTP.rb adapter, I'd be very happy to reconsider this PR for a merge :) Let me know what you think!

**Comment by linyaoli** [comment]
@delner This looks great, I'll see what I can do with it. tks

**Pull request closed without merging**
