### PR TITLE
add new redis configs

### PR DESCRIPTION
**Pull request by nerdrew**
- default_redis_service: name of the default redis service
- redis_service_include_hostname: append hostname in the service

### CODE REVIEW

**Comment by nerdrew** [comment]
cc @danielni

**Comment by palazzem** [comment]
@nerdrew we're developing a more generic way to activate / configure each integration. If you want to take a look, you may check this PR: https://github.com/DataDog/dd-trace-rb/pull/200 (it's still a work in progress)

I think it should be in sync with this PR too, that we may update together once the other one has been merged. Let us know if you have some thoughts about it!

Thank you!

**Comment by irabinovitch** [comment]
@palazzem @nerdrew Now that #200 is merged, do we need to refactor this PR?

**Comment by palazzem** [comment]
@irabinovitch yes we're testing right now some ports we did for Rails, Sidekiq etc.. Since we're  confident that this approach works, we just need a change to support service renaming without using the `Pin` object. After this last part, we can start the refactoring.

**Comment by palazzem** [comment]
Thank you very much @nerdrew for this contribution, it was very helpful to find out a different API for integration configs. I'm going to close this PR because we did a huge refactoring that ended in solving also this issue. The relevant part was the introduction of the `Configuration` object plus changing the Redis patcher: https://github.com/DataDog/dd-trace-rb/pull/256/files#diff-74e8fef7821d262b73d18f1bfd4f0ae4

We'll provide a migration guide, but for now the API will be:
```ruby
Datadog.configure do |c|
  c.use :redis, service_name: 'redis-cluster'
end
```

I will be sure your name is added to our contributors list since you raised a big concern about integrations configs. Thanks again!

**Pull request closed without merging**
