### PR TITLE
Add kernel caller to Rails/AR patcher

### PR DESCRIPTION
**Pull request by esjee**
Hello!

I'm wondering if this would be a useful addition to the tags. It seems useful for us where we can use this to figure out where exactly a query is coming from.

Curious to know what you think.

### CODE REVIEW

**Comment by esjee** [comment]
Okay, well, turns out this doesn't actually work and it's pretty tough to get the stack trace leading back to the application from ActiveSupport::Notification :see_no_evil: 

I'll do some more digging, but this PR shouldn't be merged in its current state.

**Comment by esjee** [comment]
Alright, I did some more digging and everything seems to work as expected. Thanks to the magic that is Rails, I'm now able to generate a helpful caller stack that points to your app's code. :tada:

**Comment by Willianvdv** [comment]
@esjee can you add a preview how this looks like in dd?

**Comment by delner** [comment]
@esjee I know this is super late; but could you tell me a little more about this feature? Perhaps what one might use it for as well?

**Comment by esjee** [comment]
Hi @delner, thanks for getting back to me on this PR.

I find this useful in our app since when a trace is slow, it's helpful to know where it is being called in the app and what the rest of the stacktrace looks like to get an idea of how to debug it.

If you see merit in this, I would love to get this merged since we have since reverted back to the published version of `ddtrace`, because it was too much of an hassle to have a fork stay up-to-date with upstream. 😅

**Comment by delner** [comment]
Hah, yeah I can imagine staying up to date is really difficult. Sorry we didn't get around to this earlier!

Sounds like a problem I think most of us can relate to. I'd like to understand a little more about how this typically manifests; in a general sense, where do you find the slowness comes from?

I think ideally, if possible, we'd like the trace to visually show that slow operation as a part of the graph/visualization, so it's easy and obvious to see where it's coming from. Is it be possible to create a span to cover the common offending areas of code? If this is practical, this would be preferred, but if it's not, it'd also good to know why it isn't, in which case we can consider the changes in this PR as a solution.

**Comment by esjee** [comment]
Speaking from personal experience, I found this most useful to quickly figure out where a certain query comes from. I'd use the flamegraph to determine what query or queries to look at, then use this stacktrace functionality to know what part of the application code is triggering this query.

Of course it's possible to do this without the stacktrace by grepping and having sufficient knowledge about the codebase, but the stacktrace makes it somewhat easier. 😀

Does that usecase make sense to you?

**Comment by delner** [comment]
I think so. Do you have any screenshots or example stacktraces you could share that demonstrate this? Those would be cool to see.

**Comment by esjee** [comment]
Sorry, not right now. Like I mentioned, we've removed this custom functionality a while back. I don't see how I can view traces older than 1 month in DataDog. If there is a reasonable chance that this will get merged, I'd be happy to dust it off and see if I can it to work for our instance again.

**Comment by delner** [comment]
Fair enough, I can understand that.

We'd really like the flamegraph to make it plainly obvious where the time is being spent, without needing to look at stack traces, if possible. In this case, I think to start, it would be good to add more instrumentation around the parts of the stack that seem to be the source of your slow queries. If there's something we can do to make that kind of instrumentation more accessible out of the box (say, by adding tags or other spans), then I'd be happy to help with that to see if it addresses the root issue. If the problem still isn't solved after we do that, then I think we could revisit this PR.

Also FWIW, I think we'd like to make these integrations a little more customizable in the future as well, by exposing interfaces where you could add custom code, like this backtrace tag, without having to patch the Datadog library and keep it up-to-date. We don't have clear plans for this quite yet, but I figure it might be worth mentioning since it could offer a longer term solution for getting the most out of the tracer for your needs.

**Comment by esjee** [comment]
Alright, thanks for your tiime. I don't think it's woth pursuing this feature for us at this moment.

> Also FWIW, I think we'd like to make these integrations a little more customizable in the future as well, by exposing interfaces where you could add custom code, like this backtrace tag, without having to patch the Datadog library and keep it up-to-date. We don't have clear plans for this quite yet, but I figure it might be worth mentioning since it could offer a longer term solution for getting the most out of the tracer for your needs.

This seems like a cool feature! I look forward to it.

**Pull request closed without merging**
