### PR TITLE
Load the Sidekiq client tracer on Sidekiq server

### PR DESCRIPTION
**Pull request by MXfive**
Instrument the Sidekiq client when running a Sidekiq server, Sidekiq jobs can schedule other jobs.

See documentation here: https://github.com/mperham/sidekiq/wiki/Middleware#client-middleware-registered-in-both-places

### CODE REVIEW

**Comment by delner** [comment]
@MXfive Looks good to me! We need to get CI to pass before we merge this. Looks like an unrelated issue with Excon might be causing the failures. Once we have that fixed, you'll need to rebase.

**Comment by marcotc** [comment]
Hey @MXfive, you can now rebase with master and the `excon` CI error should be gone.

Also, could you add a test to assert that these changes are working correctly?
I suggest creating a worker class that schedules another job, similar to how we test our `ErrorWorker`, for example: https://github.com/DataDog/dd-trace-rb/blob/d0c26ec7d1aae895ee47e59d900d66987606518e/test/contrib/sidekiq/server_tracer_test.rb#L12-L18

**Comment by MXfive** [comment]
@marcotc Sure I will have a go at adding test coverage this weekend.  Still looks like `jruby` tests is broken though for changes unrelated to this.

**Comment by marcotc** [comment]
👋 @MXfive, I've recently merged https://github.com/DataDog/dd-trace-rb/pull/1092, which migrated our Sidekiq tests from Minitest to RSpec, so testing should be much easier now.

**Comment by DocX** [comment]
Is this not a duplicate of #1099 ?

**Pull request closed without merging**
