### PR TITLE
remove CI module and add a dependency on datadog-ci gem

### PR DESCRIPTION
**Pull request by anmarchenko**
**What does this PR do?**
Phase 1 of the CI migration:
- remove the CI module, corresponding specs and sigs
- add datadog-ci to the gemspec as runtime dependency
- remove cucumber appraisals
- remove minitest and rspec deps from the contrib appraisal
- update lockfiles
- add datadog-ci to lib-injection scripts

**Motivation:**
Remove code duplication between gems

**Additional Notes:**
Not that it is a new runtime dependency I changed `host_inject.rb` script to install `datadog-ci` here:
https://github.com/DataDog/dd-trace-rb/pull/3128/files#diff-112f50906c11b7190b1561f372bd7298abe32cda4be0054ced470a584cffb7d3R66

Is there a way to test this? cc @TonyCTHsu 

**How to test the change?**

```bash
git clone https://github.com/DataDog/test-environment

cd test-environment

yarn

cd dd-trace-rb/jekyll
bundle add ddtrace --git "https://github.com/DataDog/dd-trace-rb.git" --branch "anmarchenko/migrate_ci_phase_1" --skip-install
bundle install --path .bundle
cd ../..

yarn test dd-trace-rb/jekyll.test.js

cd dd-trace-rb/devdocs
bundle add ddtrace --git "https://github.com/DataDog/dd-trace-rb.git" --branch "anmarchenko/migrate_ci_phase_1" --skip-install
bundle install --path .bundle
cd ../..

yarn test dd-trace-rb/devdocs.test.js
```

**For Datadog employees:**
- [ ] If this PR touches code that signs or publishes builds or packages, or handles
credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [x] This PR doesn't touch any of that.

Unsure? Have a question? Request a review!

### CODE REVIEW

**Comment by marcotc** [comment]
Looking good! 👍

**Comment by TonyCTHsu** [comment]
Perhaps we should change gemspec to add runtime dependency for ci ?

**Comment by anmarchenko** [comment]
@TonyCTHsu didn't I add it to gemspec? I think it is here https://github.com/DataDog/dd-trace-rb/pull/3128/files#diff-8b1801e03e9a166eea28410efc558b347e0b4a3bc03ab6c7283afa4479e88756R72

and all the regenerated gemfiles for appraisals now show datadog-ci (0.1.0)

**Comment by TonyCTHsu** [comment]
🕶️ I was blind

**Review by TonyCTHsu — APPROVED** [review]

**Pull request merged**
