### PR TITLE
Integrate with httpclient

### PR DESCRIPTION
**Pull request by agrobbin**
This is my first dd-trace-rb contribution, so please let me know if I've missed anything!

- [x] show a sample trace (will add as soon as I see tests pass here and I can test it in our application)

httpclient is the underlying transport framework used by [google-api-ruby-client](https://github.com/googleapis/google-api-ruby-client), and it'd be great to have it instrumented by Datadog like the other libraries it already supports. This is based on #853, when http.rb integration was added. I've implemented this in a very similar way as other HTTP client libraries that don't offer an official integration feature (i.e. a middleware stack).

### CODE REVIEW

**Review by marcotc — APPROVED** [review]
Thank you so much for your contribution, @agrobbin.
Everything looks great already!

If you are able to test these changes internally in your application it would give us a lot of confidence that the value it provides is what users (like yourself) want from `httpclient`.

Let me know if any progress with using it yourself, or if you are unable to.

Again, awesome stuff! 🎉

**Comment by agrobbin** [comment]
Thanks @marcotc! I've was able to get this out into our staging environment (which is instrumented by Datadog), and here is the first trace from this new integration:

Screen Shot 2021-01-19 at 6 47 10 PM

I've hidden a few bits of information that could be considered sensitive to our application, but tried to showcase as much information as possible.

At first glance, this looks correct, but I'd love to get your :eyes: on it to be sure!

**Comment by djlmills** [comment]
@agrobbin Thanks for tackling this. We are also using `google-api-ruby-client` and this integration is exactly what I was looking for (and contemplating building).

**Comment by agrobbin** [comment]
My pleasure @djlmills! It does seem like google-api-ruby-client is planning to move from httpclient to Faraday (googleapis/google-api-ruby-client#2348), but I'm sure that won't happen overnight, so this is definitely going to be valuable!

**Review by marcotc — APPROVED** [review]
Thank you again, @agrobbin!

Even if Google is moving away from `httpclient`, the gem still has almost 100 million downloads of its latest version (admittedly likely due to Google's API).

**Comment by marcotc** [comment]
👋 @agrobbin and @djlmills, we've just released [v0.45.0](https://github.com/DataDog/dd-trace-rb/releases/tag/v0.45.0), which includes this PR.

Please let us know if you have any further feedback on this feature!

**Pull request merged**
