### PR TITLE
test:Code coverage report

### PR DESCRIPTION
**Pull request by marcotc**
Seeing is believing: https://84200-66497320-gh.circle-artifacts.com/0/coverage/index.html

Screen Shot 2020-08-28 at 5 43 12 PM

This PR adds code coverage reporting for our CI tests.

Tests from different runs are merged together in a new `coverage` step.
A report is made available as an uploaded artifact in the `coverage` step, under `coverage/index.html`: 
Screen Shot 2020-08-28 at 5 44 54 PM

It's also possible to see the individual coverage on a per Ruby version basis: these reports will be uploaded on the same build step, under (e.g. for Ruby 2.0) `coverage/versions/test-2.0/index.html`. This is specially useful when adding support for a new Ruby version.

A report can also be generated locally by executing `bundle exec rake coverage:report` after running any of our test suites or individual tests. Results will be written to the `./coverage/` directory.

### CODE REVIEW

**Comment by brettlangdon** [comment]
Will this get reported on the PR? How can we be sure people actually look at it?

**Comment by marcotc** [comment]
@brettlangdon We don't have any plans to enforce coverage right now.

The tools that allow us to report coverage back to the PR (with a PR comment most likely) require coverage to be collected first, which is the scope of this PR.

In the future, we can use SaaS to handle the Github updates, or push them back manually ourserlves from CircleCI back to Github by giving it proper credentials.

**Comment by marcotc** [comment]
I'm going to add documentation to our `DevelopmentGuide.md`, as that's the most appropriate location today.

I'll look into adding a pull request template with this information too soon.

**Review by ericmustin — APPROVED** [review]
It's worth thinking about how we may enforce this in the future, lgtm though

**Pull request merged**
