### PR TITLE
Add pager to CI/development images + bump image to 2.7.3

### PR DESCRIPTION
**Pull request by ivoanjo**
Tiny quality-of-live improvements, see individual commit messages for details :)

### CODE REVIEW

**Comment by marcotc** [comment]
We have `vim` but no `less` 🤦.

**Comment by marcotc** [comment]
To be consistent, could you rebuild the images that are still successfully buildable (sometimes very old Ruby versions don't like to be rebuilt again today, so we can skip those). Feel free to publish those to DockerHub the same you did with 2.7 in this PR.

I ask this because we'll likely want `less` on newer Ruby versions going forward.
Also, feel free to upgrade patch version of Ruby (e.g. Ruby 3.0.1). (Not strictly required)

With this in mind, if you are not able to build older Rubies, also I'd ask you to also revert changes to their Dockerfiles, so that their Dockerfile reflects what's in the built image.

Let me know if this makes sense.

**Comment by ivoanjo** [comment]
Yeap, makes a lot of sense, will do :)

**Comment by ivoanjo** [comment]
@marcotc tag, you're it! You get to review the... small... diff :)

(with apologies to our non-Portuguese-speaking colleagues, I dedicate this sketch to you https://www.youtube.com/watch?v=sFz7EYG3_ig 🤣  )

**Review by marcotc — APPROVED** [review]
🥥

**Pull request merged**
