### PR TITLE
Presto/Elasticsearch/qLess updates

### PR DESCRIPTION
**Pull request by zhamza99**
**What does this PR do?**
Updates various integrations based on unified naming convetion:

presto - adds spankind: client and db.system: presto
elasticsearch - adds spankind: client
qLess - adds spankind: consumer

### CODE REVIEW

**Review by marcotc — APPROVED** [review]

**Comment by marcotc** [comment]
@zhamza99 is this still `do-not-merge/WIP`? Looks fine code-wise.

**Comment by zhamza99** [comment]
> @zhamza99 is this still `do-not-merge/WIP`? Looks fine code-wise.

Need to discuss this and get approval from other teams, but will notify you when it's good to go

**Comment by ivoanjo** [comment]
(Should we mark this as draft until that happens?)

**Comment by zhamza99** [comment]
@marcotc and @ivoanjo we should be good to go now

**Pull request merged**
