### PR TITLE
[ci visibility] Fix copy-paste error in teamcity env vars

### PR DESCRIPTION
**Pull request by albertvaka**
**What does this PR do?**
Fixes a copy-paste error where the wrong env var was being used to compute the pipeline URL for TeamCity.

### CODE REVIEW

**Review by ivoanjo — APPROVED** [review]
:+1: LGTM. Is this checked in system-tests or elsewhere? It looks like it'd be good to have test coverage for it :)

**Comment by ivoanjo** [comment]
P.s.: We're working on fixing the unrelated CI hiccup, we should have it back to green soon and then I'll merge in the PR :)

**Comment by albertvaka** [comment]
We have a repo (not linking it here because it is private) with tests that run against all tracers. We don't have tests for TeamCity yet but I will add them today.

**Comment by ivoanjo** [comment]
I've merged in the master branch to fix CI, making this good to go -- pressing the magic button now!

**Pull request merged**
