### PR TITLE
Add docker setup for TruffleRuby, and a few more bits to get us closer to running TruffleRuby in CI

### PR DESCRIPTION
**Pull request by ivoanjo**
Due to the issues documented in #1383 we're not yet ready to run TruffleRuby in our CI, but here's a few more improvements to get us closer to that goal.

### CODE REVIEW

**Comment by ivoanjo** [comment]
I don't understand why CircleCI is failing :(

**Comment by marcotc** [comment]
@ivoanjo the error seems to happen because https://github.com/DataDog/dd-trace-rb/blob/ivoanjo/more-truffleruby-ci-fixes/.circleci/config.yml#L243-L246
`./coverage` to exist in the working directory, but that folder didn't exit.

This is likely related to the SimpleCov changes introduced.

If you expect some runtimes (specially truffleruby) to not even create the `./coverage` directory, we need to preemptively create the `./coverage` directory in CI, just to ensure `persist_to_workspace` doesn't fail.

**Comment by ivoanjo** [comment]
Lol please ignore my repeated pushes to try to debug this with CircleCI. I kept thinking the issue was with the configuration changes and actually no -- the issue was with a typo I did in the "Add shortcut to disable simplecov" commit.

 I was beginning to think that this branch was haunted and that CircleCI had stored some magic state somewhere or something that kept it failing in different runs. Turns out...that...as..usual...the problem was between the keyboard and the chair.
 
 Senior engineer, everyone! Sigh. And now off for the weekend :)

**Review by marcotc — APPROVED** [review]
🍄♦️

**Review by delner — APPROVED** [review]

**Pull request merged**
