### PR TITLE
0.13-dev specific rubocop spec/**/** fixes

### PR DESCRIPTION
**Pull request by pawelchcki**
TODO: This PR includes changes from master that need to be merged in in separate PR.

Needs to wait for https://github.com/DataDog/dd-trace-rb/pull/433 to be merged

### CODE REVIEW

**Comment by delner** [comment]
I'm a bit confused by this commit history. "Merge master into 0.13-dev"? Is this branch based off master then merging to `0.13-dev`? This would create a really gnarly commit history.

I would recommend that we merge everything we need on `master` to `master` first. Then merge that same PR directly to `0.13-dev`. If necessary, we can merge `master` to `0.13-dev` and commit directly to `0.13-dev`, then rebase any of these `0.13-dev` changes on top of that. Would significantly untangle this history here; the goal of doing so is to keep these PRs revertable, in case something in them goes terribly wrong.

In summation, steps would be something like:

1. Merge the Rubocop changes for `master` to `master` via its PR.
2. Merge the same PR directly to `0.13-dev`, and push to `0.13-dev`
3. (If necessary) Checkout `0.13-dev` then `merge master`, and push to `0.13-dev`
4. Rebase this PR with the `0.13-dev` changes on `0.13-dev`

**Comment by pawelchcki** [comment]
Sorry @delner this PR was not yet ready for review. I put it here because to preserve the changes I've already made to 0.13 branch. But I've rebased it on latest master to do all necessary conflict resolution

In the end I think it would be best to merge master in to 0.13 branch in a separate PR after spec changes are merge to master.

Once that is done this PR commit history should shrink to around 3 commits.

**Comment by pawelchcki** [comment]
@delner I'm used to marking not yet reviewable PRs with  https://github.com/DataDog/dd-trace-rb/labels/do-not-merge%2FWIP. But I'm open to alternatives. However any comments are always appreciated 😄

**Comment by delner** [comment]
@pawelchcki I fixed many of these Rubocop problems in #442 because our `0.13-dev` build started breaking soon after I merged in `master`. I recommend rebasing this, but you might find that this pull request is defunct, and thus you also might want to close it. Let me know what you find.

**Comment by pawelchcki** [comment]
Ah indeed,  thanks for merging master in. 
Closing this PR.

**Pull request closed without merging**
