### PR TITLE
Add more scenarios to system tests

### PR DESCRIPTION
**Pull request by lloeki**
**What does this PR do?**

Enable more system test scenarios to be run in CI

**Motivation**

The default scenario covers only a limited number of tests

- Validate new developments
- Guarantee no regression

**Additional Notes**

Probably the system tests repo should provide an cross-repo reusable GitHub workflow so that we don't have to update this one manually.

**How to test the change?**

CI

### CODE REVIEW

**Comment by GustavoCaso** [comment]
The total time for running all the system tests is ~30 minutes. 

Can we reduce the CI time for running the system tests? We are currently running each scenario for each weblog variant.

Variants: 
```
- rack
- sinatra14
- sinatra20
- sinatra21
- rails32
- rails40
- rails41
- rails42
- rails50
- rails51
- rails52
- rails60
- rails61
- rails70
```

Scenarios: 

```
- DEFAULT
- REMOTE_CONFIG_MOCKED_BACKEND_ASM_DD
- REMOTE_CONFIG_MOCKED_BACKEND_ASM_FEATURES
- REMOTE_CONFIG_MOCKED_BACKEND_ASM_FEATURES_NOCACHE
- REMOTE_CONFIG_MOCKED_BACKEND_ASM_DD_NOCACHE
- APPSEC_CUSTOM_RULES
- APPSEC_MISSING_RULES
- APPSEC_CORRUPTED_RULES
- APPSEC_DISABLED
- APPSEC_LOW_WAF_TIMEOUT
- APPSEC_CUSTOM_OBFUSCATION
- APPSEC_RATE_LIMITER
- APPSEC_IP_BLOCKING
- APPSEC_REQUEST_BLOCKING
- SAMPLING
- PROFILING
```

That's 224 (14 * 16) jobs per commit. Should we try not running all the permutations?

**Comment by lloeki** [comment]
> The total time for running all the system tests is ~30 minutes.

Yeah I'm trying to reduce that by altering the matrix (e.g some tests don't depend on the framework). Also using docker image caching will help by saving a lot of rebuilds.

This is a first shot to make sure things work.

**Comment by lloeki** [comment]
`PROFILING` and `SAMPLING` scenarios are a bit on the slow side.

Unfortunately we can't [access `matrix` at the job level](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability):

```
    if: ${{ github.ref == 'refs/heads/master' || matrix.scenario != 'PROFILING' || matrix.scenario != 'SAMPLING' }}
```

**Comment by lloeki** [comment]
Using artifacts to transfer images is a bit slow too.

A better option would be to move to using `ghcr.io` since it would only transfer unknown layers, but this would pollute packages a bit. This can be mitigated with a retention policy, implementable using [actions/delete-package-versions](https://github.com/actions/delete-package-versions).

**Comment by lloeki** [comment]
An improvement, both in UI, in code clarity, and in architecture would be to leverage [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows).

Ideally these reusable workflow YAML files could even be hosted on the system tests repository (if it makes sense) or referenced from the system tests repository from this one (or the system-tests–apps-ruby repository), potentially reducing duplication.

**Comment by lloeki** [comment]
For caching, this inconsistency is annoying: https://github.com/DataDog/system-tests/pull/1046

**Comment by lloeki** [comment]
Cleanup works, but I get this strange issue, which I reported upstream:

https://github.com/actions/delete-package-versions/issues/101

**Comment by lloeki** [comment]
> The total time for running all the system tests is ~30 minutes.

Last run was ~16min. That's without the full benefit of docker build caching though, until [this is merged](https://github.com/DataDog/dd-trace-rb/pull/2738#issuecomment-1497790208).

**Review by marcotc — APPROVED** [review]

**Comment by lloeki** [comment]
Improvements and fixes delayed to later PRs:

- proper use of caching for builds ([see here](https://github.com/DataDog/dd-trace-rb/pull/2738#issuecomment-1497790208))
- reusable workflows ([see here](https://github.com/DataDog/dd-trace-rb/pull/2738#issuecomment-1497604791))
- fix transient image tag deletion ([see here](https://github.com/DataDog/dd-trace-rb/pull/2738#issuecomment-1498116414))

Them not being in here has little impact compared to the value added so I'll be merging this PR so that it doesn't linger on.

**Pull request merged**
