### PR TITLE
APM SDK Terminology

### PR DESCRIPTION
**Pull request by brett0000FF**
**What does this PR do?**

- Updates single-sourced public documentation to replace "tracer" and "tracing library" with "APM SDK".

**Motivation:**

https://github.com/DataDog/documentation/pull/24255/

**Additional Notes:**

Please don't merge into `release` until the `documentation` PR linked above is merged.

**How to test the change?**

Unsure? Have a question? Request a review!

### CODE REVIEW

**Comment by ivoanjo** [comment]
I guess:

* https://github.com/DataDog/dd-trace-rb/blob/master/README.md
* https://github.com/DataDog/dd-trace-rb/blob/master/datadog.gemspec#L21
* the repo description 
image

should also be updated to reflect this once it's ready to go?

**Review by aliciascott — APPROVED** [review]
this looks good, I'll let you merge once the related PR is reviewed (editorial review)

**Comment by brett0000FF** [comment]
> should also be updated to reflect this once it's ready to go?

@ivoanjo - Yeah, I talked about this with @tushar-datadog . I think for consistency's sake, we should keep the terminology consistent wherever possible.

**Comment by aliciascott** [comment]
Hey @brett0000FF is this still one you are planning on merging ? Just noticed it was in my stale queue but also looks like there is a merge conflict now :)

**Comment by ivoanjo** [comment]
Hey @brett0000FF do you know the status of the renaming work? Should we go ahead with this PR still?

**Comment by brett0000FF** [comment]
Pausing this effort for now. ⏸️

**Pull request closed without merging**
