### PR TITLE
Use Ruby 2.7.6 in CircleCI

### PR DESCRIPTION
**Pull request by lloeki**
Depends on https://github.com/DataDog/dd-trace-rb/pull/2398

### CODE REVIEW

**Review by TonyCTHsu — APPROVED** [review]

**Comment by lloeki** [comment]
Noting a failure to install appraisal, bundler seems to trip upon itself:

```
NoMethodError: undefined method `full_name' for nil:NilClass
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:124:in `block (2 levels) in check_for_unmet_dependencies'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:123:in `each'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:123:in `block in check_for_unmet_dependencies'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:122:in `each'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:122:in `check_for_unmet_dependencies'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:100:in `call'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:71:in `call'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/installer.rb:254:in `install_in_parallel'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/installer.rb:209:in `install'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/installer.rb:89:in `block in run'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/process_lock.rb:12:in `block in lock'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/process_lock.rb:9:in `open'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/process_lock.rb:9:in `lock'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/installer.rb:71:in `run'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/installer.rb:23:in `install'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli/install.rb:62:in `run'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli.rb:257:in `block in install'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/settings.rb:131:in `temporary'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli.rb:256:in `install'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli.rb:31:in `dispatch'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli.rb:25:in `start'
  /usr/local/bundle/gems/bundler-2.3.26/exe/bundle:48:in `block in <top (required)>'
  /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
  /usr/local/bundle/gems/bundler-2.3.26/exe/bundle:36:in `<top (required)>'
  /usr/local/bundle/bin/bundle:25:in `load'
  /usr/local/bundle/bin/bundle:25:in `<main>'
```

**Comment by marcotc** [comment]
> Noting a failure to install appraisal, bundler seems to trip upon itself:
An old bundler bug, fixed in bundler 2.3.0: https://github.com/rubygems/rubygems/issues/5088

**Comment by lloeki** [comment]
> An old bundler bug, fixed in bundler 2.3.0

... except this is `bundler-2.3.26` :(

**Comment by marcotc** [comment]
😢

**Comment by lloeki** [comment]
Looks like bundler has a regression?

```
gem install bundler -v 2.3.23
bundle _2.3.23_ exec appraisal install # fails
gem install bundler -v 2.3.20
bundle _2.3.23_ exec appraisal install # works
```

**Comment by lloeki** [comment]
2.3.21 seems affected too.

**Comment by marcotc** [comment]
> 2.3.21 seems affected too. Watch out, rerun after each fail may make you go through bit by bit.
> 
> Confirming it works with 2.3.20:
> 
> ```
> docker volume rm dd-trace-rb_bundle-2.7
> docker-compose run --rm tracer-2.7 /bin/bash -c 'rm -vf Gemfile.lock && bundle install && gem install bundler -v 2.3.20 && bundle _2.3.20_ exec appraisal generate && bundle _2.3.20_ exec appraisal install'
> ```

I get this error with the instructions above:
```
>> bundle check --gemfile='/app/gemfiles/ruby_2.7.6_rails5_semantic_logger.gemfile' || bundle install --gemfile='/app/gemfiles/ruby_2.7.6_rails5_semantic_logger.gemfile' --retry 1
Resolving dependencies...
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies....
Bundler could not find compatible versions for gem "sorbet":
  In ruby_2.7.6_rails5_semantic_logger.gemfile:
    sorbet (= 0.5.9672)

    spoom (~> 1.1) was resolved to 1.1.12, which depends on
      sorbet (>= 0.5.9204)
Bundler could not find compatible versions for gem "sorbet-static":
  In ruby_2.7.6_rails5_semantic_logger.gemfile:
    sorbet (= 0.5.9672) was resolved to 0.5.9672, which depends on
      sorbet-static (= 0.5.9672)

Could not find gem 'sorbet-static (= 0.5.9672)' with platform 'ruby', which is required by gem 'sorbet (= 0.5.9672)', in rubygems
repository https://rubygems.org/ or installed locally.

The source contains the following gems matching 'sorbet-static (= 0.5.9672)':
  * sorbet-static-0.5.9672-java
  * sorbet-static-0.5.9672-universal-darwin-14
  * sorbet-static-0.5.9672-universal-darwin-15
  * sorbet-static-0.5.9672-universal-darwin-16
  * sorbet-static-0.5.9672-universal-darwin-17
  * sorbet-static-0.5.9672-universal-darwin-18
  * sorbet-static-0.5.9672-universal-darwin-19
  * sorbet-static-0.5.9672-universal-darwin-20
  * sorbet-static-0.5.9672-universal-darwin-21
  * sorbet-static-0.5.9672-x86_64-linux
```
which seems like a regular dependency conflict.

I acknowledge that this is not the same error as CI, just reporting that the steps provided might not give everyone the same error.

**Comment by lloeki** [comment]
Ah, that must be because I'm running this on aarch64, which does not have sorbet. Conditionals in gemfiles are such a bad, bad thing!

I guess `sorbet` should be in a group, and has no business being in appraisals.

**Comment by lloeki** [comment]
Notably, I ran this to make sure all locks have both platforms:

```
docker-compose run --rm tracer-2.7 /bin/bash
cd gemfiles
ls -1 ruby_2.7.6*.gemfile | while read -r gemfile; do bundle lock --gemfile=$gemfile --add-platform aarch64-linux; done
ls -1 ruby_2.7.6*.gemfile | while read -r gemfile; do bundle lock --gemfile=$gemfile --add-platform x86_64-linux; done
```

There are a couple of those locks that still have `ruby` as a platform, I'm not entirely sure why.

**Comment by lloeki** [comment]
Guess what, it worked! The 2.7 build job went through, and now the 2.7 test job fails with the same error as in https://github.com/DataDog/dd-trace-rb/pull/2414

**Review by marcotc — APPROVED** [review]

**Comment by lloeki** [comment]
Changed the base to depend on https://github.com/DataDog/dd-trace-rb/pull/2422

**Comment by lloeki** [comment]
Changed base to https://github.com/DataDog/dd-trace-rb/pull/2425

**Pull request merged**
