### PR TITLE
Enable Telemetry by default

### PR DESCRIPTION
**Pull request by marcotc**
All system-tests are now passing and fixes have been merged into `master` already to address all inconsistencies.
Telemetry is ready to go!

#2761 will ensure `dd-trace-rb` triggers all telemetry tests on each commit. All tests are already passing in the system-tests repository itself. It's just a matter of making sure they keep passing.

### CODE REVIEW

**Comment by GustavoCaso** [comment]
@marcotc should we make sure to merge https://github.com/DataDog/system-tests/pull/1048, validate all test passes on our end and then merge this PR?

**Comment by marcotc** [comment]
@GustavoCaso merged the system-tests in question, running it again now.

**Comment by ivoanjo** [comment]
FYI the tests showing up as pending are fixed in https://github.com/DataDog/dd-trace-rb/pull/2772 so they're OK to ignore

**Comment by TonyCTHsu** [comment]
We've have [potential flaky specs](https://github.com/DataDog/dd-trace-rb/pull/2555) related to enabling telemetry by default. Is is still the case?

**Comment by GustavoCaso** [comment]
@marcotc I don't see the `TELEMETRY` run against this branch? Should we rebase master on this one?

**Comment by marcotc** [comment]
@GustavoCaso They have arrived!
Screenshot 2023-04-14 at 11 15 33 AM

**Review by GustavoCaso — APPROVED** [review]

**Pull request merged**
