### PR TITLE
Update dd-apm-test-agent to 1.18.0 (current release)

### PR DESCRIPTION
**Pull request by p-datadog**
**What does this PR do?**

Updates dd-apm-test-agent to 1.18.0 (current release)

**Motivation:**

Our version is outdated (1.12).

**Additional Notes:**

**How to test the change?**
Check if CI is green

Unsure? Have a question? Request a review!

### CODE REVIEW

**Review by ivoanjo — APPROVED** [review]
:+1: Looks reasonable to me, and it's easy to undo if we find issues

**Comment by p-datadog** [comment]
Is this PR OK to merge with the failing test? I restarted it twice and it's still failing.

**Comment by ivoanjo** [comment]
I think the `onboarding_tests_installer` thing has been failing on every PR I saw today... I think we need to poke at our colleagues to look at what's up unhealthy :eyes:

**Comment by p-datadog** [comment]
:+1:

**Pull request merged**
