### PR TITLE
Support for Ruby 2.7

### LINKED ISSUE #805: Support for Ruby 2.7
With Ruby 2.7 [scheduled to be released December 2019](https://www.ruby-lang.org/en/news/2019/05/30/ruby-2-7-0-preview1-released/), `dd-trace-rb` should be ready to support it on release date.

There are a few confirmed blockers affecting the latest release, `2.7.0-preview1`:
#### Blockers
- `2.7.0-preview1` is affected by https://bugs.ruby-lang.org/issues/15891, which prevents `dd-trace-rb` from starting up successfully. This has been fixed in Ruby `master` branch, which is still unreleased.
#### Contrib
- `grpc`, [as of version 1.23.0](https://rubygems.org/gems/grpc/versions/1.23.0), doesn't support Ruby 2.7, failing installation with: `grpc requires Ruby version >= 2.3, < 2.7.dev`

### PR DESCRIPTION
**Pull request by marcotc**
Fixes #805 

This PR adds a new branch to our CI pipeline and Rakefile to support testing `ddtrace` with Ruby 2.7.

No incompatibilities have been found with `ddtrace` code.

gRPC is the only gem that does not successfully install with Ruby 2.7, explicitly failing with `grpc requires Ruby version >= 2.3, < 2.7.dev`, so we skip testing it with Ruby 2.7 until an update is released.

### CODE REVIEW

**Comment by brodock** [comment]
We have release candidates for ruby 2.7 now: https://www.ruby-lang.org/en/news/2019/12/21/2-7-0-rc2-released/

**Comment by marcotc** [comment]
We are getting very close, 🤞 the [Ruby Docker Hub images](https://hub.docker.com/_/ruby/) (backed by [the official GitHub repo](https://github.com/docker-library/ruby)) are release soon, to allow us to test it in our CI.

**Comment by marcotc** [comment]
GA images have been released, updated the PR accordingly.

I'm fighting bundler versions now, which should be the last thing we need to do.

**Comment by marcotc** [comment]
I found [a bug in Appraisal](https://github.com/thoughtbot/appraisal/issues/162) that prevents us from using the latest version of `bundler` (>= 2.1.3).

For the time being, the container for Ruby 2.7 is using the version of `bundler` available at publish date, December 28th 2019, which is `2.1.2`.

We can reassess after the appraisal issue receives further updates.

There is not impact on our CI behaviour and bundler changes in the last week have only been minor patches that don't seem to impact us at first read.

**Pull request merged**
