### PR TITLE
Fixing anchors

### PR DESCRIPTION
**Pull request by l0k0ms**
Fixes anchors for the documentation.

### CODE REVIEW

**Comment by marcotc** [comment]
Hi @l0k0ms, thank you for taking the time help this the documentation!

Your proposed changes fix the [published documentation](https://docs.datadoghq.com/tracing/setup/ruby/#net-http), but unfortunately break [GitHub markup](https://github.com/DataDog/dd-trace-rb/blob/gus/doc-a11y-issues-fix/docs/GettingStarted.md#net-http).

We could add custom anchor workarounds in our markup to make it work with both systems, but that would make maintaining this documentation much harder as breaking these custom anchors would be symptomless here at GithHub.

I think the best solution would be to make sure the GitHub document always renders properly, and make necessary changes to our documentation pipeline, if possible.

By the way, this comment above only applies to `net-http`; the `rest-client` changes look good!

**Comment by delner** [comment]
@marcotc Not sure what you mean that the markup is broken? From what I can see, the anchor works as do the links.

**Comment by marcotc** [comment]
@delner  If you navigate to this branch's [GettingStarted.md](https://github.com/DataDog/dd-trace-rb/blob/gus/doc-a11y-issues-fix/docs/GettingStarted.md#table-of-contents) and click "Net/HTTP" in the "Table of Contents" it doesn't jump to the anchor.

**Comment by delner** [comment]
Got it, yeah the the Net/HTTP one is broken, but Rest Client one works fine.

**Comment by l0k0ms** [comment]
@marcotc it may break the anchor link in github, but the current link: 
* Doesn't work in the gem doc http://gems.datadoghq.com/trace/docs/#nethttp 
* Doesn't work in the public documentation too

If we make the assumption that people would consume doc in one of those 2 places. At least one of them should work.

**Comment by l0k0ms** [comment]
Two questions here: 

1. Why do we need a hard written ToC in the file? It's auto-generated in the public doc, and it's auto-generated in the gem doc, isn't it? 
2. In case of conflict in terms of anchor interpretation, which medium wins?

Or maybe we should just fix the section title to remove non alphanumeric characters ?

**Comment by apigirl** [comment]
+1 for removing the hard coded toc

**Comment by delner** [comment]
I don't think removing the ToC here provides a good experience for our Github users, as GitHub does not auto-generate a ToC and it's helpful for navigating length documentation. I think it would be better to strip it out downstream where necessary, to tailor that experience appropriate to its medium.

Regardless, we are planning on re-organizing our docs into smaller pieces here on Github; I think there's a good chance that will affect how the ToC appears and how it impacts other documentation downstream. Let's wait on that.

**Pull request closed without merging**
