### PR TITLE
Add require: false to Gemfile to allow unit tests

### PR DESCRIPTION
**Pull request by pboling**
Unit Testing in a Rails project that uses the ddtrace gem is difficult (impossible?) unless you do `require: false` in the Gemfile.

### CODE REVIEW

**Comment by delner** [comment]
Hey @pboling , thanks for bringing this up.

Is it that `gem 'ddtrace'` is causing the test suite loading to fail, or that your tests are failing because `ddtrace` is sending traces in a test suite that expects to not send web requests?

If it's the latter, you should be able to disable the tracer in your test suite, by adding something like:

```
# config/initializers/datadog.rb
Datadog.configure do |c|
  if ENV['RAILS_ENV'] == 'test'
    c.tracer enabled: false
  end

  # More tracer configuration..
end
```

If it's the prior, could you provide some stack traces?

**Comment by pboling** [comment]
The issue is that it is sending traces, and I was unable to find the enabled option.  I looked for quite a long time.  I skimmed the source, I grepped it, I couldn't find anything that explained how to do testing when you have ddtrace on a project.

The `enabled` setting makes sense, but it is *not* advanced usage, so it is rather hidden in the documentation, and it doesn't even mention the testing use case.  Testing is Rule #1, and should be the most basic usage.  How to turn it off should be front and center in the Readme, IMO.

I apologize that this is very frustrating for me - this is not what developer happiness feels like.

**Comment by delner** [comment]
I hear you. The gem doesn't really emphasize test support as of yet, but there are plans for adding such support. Ideally it'd be nice to see a testing tracer being used in test suites, which provides an option to assert on traces it generates.

There's another pull request opened that provides a test tracer that might be of interest. https://github.com/DataDog/dd-trace-rb/pull/187

**Comment by pboling** [comment]
I will report back when I have a chance to try it out.  Thanks for the help.  A real test tracer would be amazing!

**Comment by pboling** [comment]
Yes, that worked.  Looking forward to even more testing support!

**Comment by delner** [comment]
Glad to hear it. I'll let you know when we add more support.

**Pull request closed without merging**
