### PR TITLE
359: Add block back into render call

### PR DESCRIPTION
**Pull request by dorner**

### CODE REVIEW

**Comment by dorner** [comment]
@delner `render_partial` doesn't take a block like `render` does. The block is handled separately.

**Comment by delner** [comment]
Cool, the context there is helpful.

But I think the point of adding block to the partial renderer still applies, since the PartialRenderer [does actually take a block](https://github.com/rails/rails/blob/master/actionview/lib/action_view/renderer/partial_renderer.rb#L297) for `render` and [the tracer isn't fowarding the block](https://github.com/wishabi/dd-trace-rb/blob/b3f848044035fd330fc43fcee80200c633c596c4/lib/ddtrace/contrib/rails/core_extensions.rb#L98). Or am I misunderstanding?

**Comment by dorner** [comment]
@delner yep. :) If you follow the code, here's what's happening:
* PartialRender calls `render`
* This takes a block, i.e. a Proc *as an argument* (not an actual Ruby block)
* The block is saved in an instance variable
* `render` then calls `render_partial` *without any arguments*
* `render_partial` uses the instance variable saved previously to render

The patcher patches the `render_partial` method, not the `render` method, so all of the block handling should be managed entirely without the patched method caring about it.

**Comment by delner** [comment]
Oh, whoops, you're right: `block` is being passed as a normal parameter in the PartialRenderer. My eye was just automatically adding the `&` to it. Looks like the `&block` in `def render_with_datadog(*args, &block)` patch for PartialRenderer doesn't actually match the parameter list for the function its displacing.

We should probably remove that extraneous `&block` from that function def, but otherwise it looks like it shouldn't suffer the same issue. Thanks for correcting me!

**Pull request merged**
