### PR TITLE
Update appraisal gemfile.lock with platform aarch64-linux

### PR DESCRIPTION
**Pull request by TonyCTHsu**
**What does this PR do?**
Introduce `aarch64-linux` platform for `gemfile.lock`

**Motivation**
Adding this would make re-resolving for the addition of that platform.

### CODE REVIEW

**Comment by marcotc** [comment]
How did you generate these?

**Comment by TonyCTHsu** [comment]
> How did you generate these?

These are generate by `bundle exec appraisal install` in the container.

**Review by marcotc — APPROVED** [review]

**Comment by ivoanjo** [comment]
I'm not against merging this, but I think this will generate some flip-flopping of the gemfile.lock files:

* Bundler set `libdatadog` and `libddwaf` as "...-aarch64-linux" which I'm assuming will lead the next person who updates this to have to flip them back to "...-x86_64-linux"
* Sorbet is not available on arm64, so the dependency got removed. Again, this will lead to a back-and-forth the next time someone updates this from an x86-64 machine

I'm curious: @TonyCTHsu could you tell us more on how this helps your development process? Presumably we all need to run `bundle exec appraisal install` anyway to develop locally so my question is, what is the advantage in committing these changes?

**Comment by TonyCTHsu** [comment]
I guess that is partially true that this could become a back and forth thing for those native extensions.

My idea was to make bundler to support multiple platforms, which could be achieve by adding the platform [at the bottom of the lock file](https://github.com/DataDog/dd-trace-rb/pull/2179/files#diff-9591fe7950defffd3a2be4242f39fc503441022a2a51eb8f0db4902c47b59301R155-R157), this is usually accomplished by `bundle lock --add-platform PLATFORM`. 

However, Appraisal is only using `bundle install` under the hood for `bundle exec appraisal install`. Hence, I could not run `bundle lock --add-platform` from console in this case.

`bundle install` would generate the lock file on the first run and leverage the lock file for subsequent runs. so I think it is ok to introduce the changes in such way.

**Review by ivoanjo — APPROVED** [review]
Ok so I was half correct. If I run `bundle exec appraisal install` bundler ADDS platform-specific variants for x86-64 for the binary stuff (so that doesn't change), and it re-adds sorbet:

```
diff --git a/gemfiles/ruby_3.0.3_contrib.gemfile.lock b/gemfiles/ruby_3.0.3_contrib.gemfile.lock
index 6665c4e15..e97f02cca 100644
--- a/gemfiles/ruby_3.0.3_contrib.gemfile.lock
+++ b/gemfiles/ruby_3.0.3_contrib.gemfile.lock
@@ -1448,8 +1448,11 @@ GEM
       addressable (>= 2.4)
     jsonapi-renderer (0.2.2)
     libdatadog (0.7.0.1.0-aarch64-linux)
+    libdatadog (0.7.0.1.0-x86_64-linux)
     libddwaf (1.3.0.2.0-aarch64-linux)
       ffi (~> 1.0)
+    libddwaf (1.3.0.2.0-x86_64-linux)
+      ffi (~> 1.0)
     loofah (2.15.0)
       crass (~> 1.0.2)
       nokogiri (>= 1.5.9)
@@ -1625,9 +1628,17 @@ GEM
       rake (~> 12.3)
       serverengine (~> 2.1.0)
       thor
+    sorbet (0.5.9672)
+      sorbet-static (= 0.5.9672)
+    sorbet-runtime (0.5.10217)
+    sorbet-static (0.5.9672-x86_64-linux)
     sorted_set (1.0.3)
       rbtree
       set (~> 1.0)
+    spoom (1.1.11)
+      sorbet (>= 0.5.9204)
+      sorbet-runtime (>= 0.5.9204)
+      thor (>= 0.19.2)
     sqlite3 (1.4.2)
     statsd-ruby (1.5.0)
     sucker_punch (3.0.1)
@@ -1733,6 +1744,8 @@ DEPENDENCIES
   simplecov!
   sinatra
   sneakers (>= 2.12.0)
+  sorbet (= 0.5.9672)
+  spoom (~> 1.1)
   sqlite3 (>= 1.4.2)
   sucker_punch
   typhoeus
```

Being this the case, the only remaining issue is sorbet appearing and disappearing. I think it would be nice to address that, but I don't see that as a blocker for this PR.

**Comment by TonyCTHsu** [comment]
I tested out how it looks like for multiple platforms. It would create multiple entries for a single gem with compatible native extensions. 

here are steps I tested.

1.  Delete local `Gemfile.lock` to start from scratch
2. `bundle install`  => this creates a `Gemfile.lock` with 

```
+    libdatadog (0.7.0.1.0)
+    libddwaf (1.3.0.2.0-arm64-darwin)
+      ffi (~> 1.0)
```
and 
```
+PLATFORMS
+  arm64-darwin-21
```
3 `bundle lock --add-platform aarch64-linux` 

```
     libdatadog (0.7.0.1.0)
+    libdatadog (0.7.0.1.0-aarch64-linux)
+    libddwaf (1.3.0.2.0-aarch64-linux)
+      ffi (~> 1.0)
     libddwaf (1.3.0.2.0-arm64-darwin)
       ffi (~> 1.0)
```
and
```
 PLATFORMS
+  aarch64-linux
   arm64-darwin-21
```
4. `bundle lock --add-platform x86_64-linux`
```
     google-protobuf (3.21.3)
+    google-protobuf (3.21.3-x86_64-linux)
     hashdiff (1.0.1)
     json (2.6.2)
     json-schema (2.8.1)
       addressable (>= 2.4)
     libdatadog (0.7.0.1.0)
     libdatadog (0.7.0.1.0-aarch64-linux)
+    libdatadog (0.7.0.1.0-x86_64-linux)
     libddwaf (1.3.0.2.0-aarch64-linux)
       ffi (~> 1.0)
     libddwaf (1.3.0.2.0-arm64-darwin)
       ffi (~> 1.0)
+    libddwaf (1.3.0.2.0-x86_64-linux)
+      ffi (~> 1.0)
```
and 
```
 PLATFORMS
   aarch64-linux
   arm64-darwin-21
+  x86_64-linux
```

**Pull request merged**
