### PR TITLE
Update CHANGELOG to mention YJIT stat tracking

### PR DESCRIPTION
**Pull request by HeyNonster**
In #2711, I forgot to include an update to the CHANGELOG.

**What does this PR do?**
Only updates the CHANGELOG.

**Motivation**
Wanting to mention the YJIT stat tracking so that folks interested in tracking them don't miss it.

**Additional Notes**
n/a

**How to test the change?**
n/a documentation only

### CODE REVIEW

**Review by marcotc — APPROVED** [review]

**Comment by marcotc** [comment]
👋, @HeyNonster, we normally build the changelog from GitHub pull request titles and descriptions when we are preparing a new release.

It's totally ok to have it added now (and helpful); I just wanted to let you know that this entry wasn't technically missing from the original PR (our regular process doesn't require it at PR time.)

**Comment by HeyNonster** [comment]
> 👋, @HeyNonster, we normally build the changelog from GitHub pull request titles and descriptions when we are preparing a new release.
> 
> It's totally ok to have it added now (and helpful); I just wanted to let you know that this entry wasn't technically missing from the original PR (our regular process doesn't require it at PR time.)

Awesome, thanks @marcotc :)

**Comment by delner** [comment]
@marcotc What's the resolution on this one? Should we merge or close this?

**Comment by marcotc** [comment]
Merge it! 👍

**Pull request merged**
