### PR TITLE
Prepare parametrized PG query for showing query parameters in web panel

### PR DESCRIPTION
**Pull request by unavailabl3**
Since Rails 5 has parametrizied query statement like this:
SELECT * FROM 'items' WHERE 'item'.'id' = $1 [['id',123]]
Params are not shown in app.datadoghq.com panel beacuse of obfuscation.
So in panel app.datadoghq.com we see:
`SELECT * FROM 'items' WHERE 'item'.'id' = ?`
Instead of:
`SELECT * FROM 'items' WHERE 'item'.'id' = 123`
This commit ads feature (for ActiveRecord/Postgresql) to see params (to turn off params obfuscation).

### CODE REVIEW

**Comment by delner** [comment]
Thanks for the PR @unavailabl3! Have you tested this with an app and see if it had an effect?

My suspicion is that any changes on the Ruby end won't work, because the agent deliberately obfuscates parameters such as these; it does this to group like queries and to remove PII.

**Comment by unavailabl3** [comment]
Yes, it is working. I see all parameters in my panel, but may be this code bypasses agent obfuscation if you say I couldn't do it from Ruby end.
I was talking to your Datadog support and it is very sad, that you do not provide feature to turn off obfuscation, because many people want to analyze queries and also copy them to DB EXPLAIN SQL.
Image of Trace

**Comment by delner** [comment]
Hmmmm, this is an interesting consideration and good feedback. I'm going to consult with the team on this and follow up as soon as I have something to share. (Thanks for the suggestion!)

**Comment by delner** [comment]
Okay, so after talking with the team, I think we want to give this kind of feature a more comprehensive treatment than what we'd be able to provide from just Ruby. So I'm going to close this PR for now.

The plan is we'll use this specific PR as a basis/use case for improvements to our SQL support, as we internally develop a better means of dealing with this kind of obfuscation. I'll keep you updated on any updates as I receive them; thanks for bringing this to our attention! Community PRs like this really help us improve the product and we appreciate the contribution!

**Pull request closed without merging**
