### PR TITLE
Add makara support with ActiveRecord

### PR DESCRIPTION
**Pull request by marcotc**
This PR adds support for individually configuring primary vs replica databases with the [`makara` gem](https://rubygems.org/gems/makara).

```ruby
c.use :active_record, describes: { makara_role: 'primary' }, service_name: 'primary-db'
```

This support is specifically added for the [Makara ActiveRecord Database Adapter](https://github.com/instacart/makara#activerecord-database-adapter), thus tied to ActiveRecord notification events. This greatly simplifies the implementation.

All versions of `makara` will be supported by `ddtrace` with this change (the documentation says `>= 0.3.5` because that's the first publicly available gem at RubyGems for Makara).

The gem itself is relatively popular (5.8M downloads) and requests for this feature have come from users before.

### CODE REVIEW

**Review by delner — COMMENTED** [review]
Some solid work here, as usual @marcotc !

I have some strategic questions though; is the ActiveRecord integration the best place for this? Or does it make sense to have a `makara` integration itself that extends or adds to the `active_record` integration?

Looks like Makara is standalone, but it does have this AR adapter. I think in the ideal world, some form of the second makes more sense (since ActiveRecord has nothing to do with Makara, even if Makara has something to do with ActiveRecord.) However, this would likely require some kinda plugin mechanism to make work.

I want to respect the principle of YAGNI, so maybe this isn't the right time to do this kind of plumbing when there's only 1 AR extension (Makara), but I could see more in the future. When that happens, I think such work would be warranted to keep clean boundaries between packages/dependencies/integrations.

You've done a nice job putting most of the Makara stuff into a module and composing that in; is there anything else we can/should do internally to the AR integration here, such that if/when that time comes to extract Makara, we can do that with less pain?

Would like to hear your thoughts!

**Comment by marcotc** [comment]
My initial approach was to add a separate instrumentation for `makara`, as it has a [Proxy class](https://github.com/instacart/makara#basic-usage) that implements its core behaviour.

While trying to surface that integration data alongside the ActiveRecord instrumentation, I noticed that the visibility users were looking for wasn't presented clearly anymore: a Makara span, created between the calling code and the ActiveRecord span, was now the place with access to the richest database information in `ddtrace`, thus the point where users would likely separate their application service from their database service (where a separate database service name would be introduced).

This meant that the Makara span now had to be just as rich as the ActiveRecord one, having all the connection fields required for a rich display as well as for performing a full `describes:` matching. This causes a problem as, at Makara level, the connection object is opaque: Makara is a generic connection proxy thus doesn't know, for example, what host or port are.

With this scenario, I wasn't able to come up with a solution that allow users to have a new Makara span while preserving the richness of the existing ActiveRecord information they have today. It is technically possible to find this information, but it requires the Makara integration to "look-ahead" down the instrumentation stack (either literally, by inspecting child spans, or indirectly by calling parts of the ActiveRecord instrumentation code that would now be shared).

It's a similar situation to our Rack integration (how it needs the Rails layer to provide a rich resource name) or our Rack `request_queuing` spans (how it is not a separate, standalone integration, but an extension to the Rack one).

In the end, I think that adding a standalone Makara instrumentation makes sense for users of Makara that are not also using one of our supported SQL integrations (ActiveRecord or Sequel). If they are using one of the supported SQL integrations, I think that augmenting it with Makara information makes more sense, as it provides the information they need in the place it has the most value.

This is not a perfect match for how the instrumentation information should be represented: ideally everything would have its own layer. But currently, the configuration and presentation values provided by denormalizing Makara back into ActiveRecord is much greater than the value provided by strictly adhering to the internal application structure.

As a side note, all the [uses cases of Makara I could find](https://github.com/instacart/makara/network/dependents?package_id=UGFja2FnZS0yNzc3MTU%3D) and all user requests indeed go through ActiveRecord: either directly, like [mastodon](https://github.com/tootsuite/mastodon/blob/main/Gemfile#L9-L16), or through the 
[distribute_reads](https://github.com/ankane/distribute_reads) gems.

**Comment by delner** [comment]
> I wasn't able to come up with a solution that allow users to have a new Makara span while preserving the richness of the existing ActiveRecord information they have today.

I'm not suggesting there be a Makara span (unless there were some kind of distinct operation that's pure Makara); instead, I was thinking a `makara` integration would have an `active_record` module that would "plug in" to some kind of API implemented on the `active_record` integration. e.g. `Contrib::ActiveRecord::Integration.add_plugin(Contrib::Makara::ActiveRecord::Plugin)` or some such thing. Such a plugin would presumably add the `MakaraConnectionResolver` (as you've already written it) to the `active_record` integration, perhaps in some kind of middleware scheme.

Caveat to this being 1) this is a case of YAGNI until we see other integrations need a similar API and 2) I'm not missing something important about the scheme here that doesn't jive with this.

This is not blocking feedback as it's not necessarily actionable at this moment, it's more of a "food for thought" consideration while we review the nature of this feature.

**Comment by marcotc** [comment]
Ahh, I can see that.

I think this would fit in as part of the not-too-infrequent request from users to customize how to the tracer handles certain parts of integrations. Normally such requests are around changing the content of span tags, but the resolver can also be an extension point.

One concern we always have around extension points is how to avoid the overhead of consulting a possibly empty middleware stack (e.g. check a middleware stack for each span for each integration).

Looking at this PR, the least intrusive extension point is not the public `#resolve` and `#add` methods, but the internal `normalize_*` methods. This means that even if we had a nice middleware chain for resolvers, the implementation of this Makara support through extensions would like unnecessarily perform repeated operations over the input to accomplish the same result as this PR. To be fair, this is likely always the case for user-accessible extension points.

I'm thinking that, for solving most of our extension points concerns around overhead, we could document how to extend the tracer using the native Ruby class hierarchy (`Module#include`, `Module#prepend`). This would provide maximum extensibility and performance, at the expense of having less structure (managed middleware chain).

I'm tabling this discussion for now, at least in the context of this PR, and I'll capture our discussion for planning an official extension API.

**Comment by delner** [comment]
Yeah, fair sensible considerations all around. Once tests are passing, I'll approve this.

**Review by delner — APPROVED** [review]
:+1:

**Pull request merged**
