### PR TITLE
Allow overriding service name for rails ActiveJob

### LINKED ISSUE #1703: ActiveJob service name prefix
https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/contrib/rails/framework.rb#L135

We'd love to be able to override this service name, and tuck the AJ operation into the main service.

### PR DESCRIPTION
**Pull request by hatstand**
Fixes #1703

### CODE REVIEW

**Review by marcotc — CHANGES_REQUESTED** [review]
Thank you for this contribution, @hatstand!

The only thing missing is a documentation update, letting everyone know this new setting is available in the Rails integration.

Could you add the respective documentation for this new setting here? https://github.com/DataDog/dd-trace-rb/blame/9e75a243be861d5963e4b0c55b4223b607bae30e/docs/GettingStarted.md#L1503-L1514

**Comment by hatstand** [comment]
@marcotc Done in 4e38ff718b057daeaed5ae4090245a72866a4295

**Review by marcotc — APPROVED** [review]
Thank you, @hatstand! 🙇

**Comment by marcotc** [comment]
👋 Thank you again @hatstand, https://github.com/DataDog/dd-trace-rb/releases/tag/v0.54.0 was just released, including this feature.

**Pull request merged**
