### PR TITLE
Sequel integration

### PR DESCRIPTION
**Pull request by palin**

### CODE REVIEW

**Comment by delner** [comment]
Hey @palin , thanks for putting this together! Love seeing support for new libraries. We've been particularly interested in adding Sequel for some time now, too, so this is great.

I'll take a look through this when you feel it's ready for review. In the mean time, since we do require tests for contributions, I'd suggest adding some RSpec tests that exercise this new integration.

**Comment by palin** [comment]
Hi @delner, sorry didn't see your comment before.
The code works but is dirty. There are probably lines which should be removed.
We will try to add some rspec tests to it soon.
Thanks

**Comment by palin** [comment]
@delner Thank you for your response. We looked through the #171 and it looks good. Do you have any ETA for merging that PR?

**Comment by delner** [comment]
@palin I don't yet, other to say that it's on our queue, albeit unscheduled. I'll can let you know as things develop.

**Comment by delner** [comment]
Hey @palin , we started rebasing/updating #171 with the intention to merge it soon. Going to close this PR in favor of that one. Feel free to add any feedback you might have about Sequel on that, and we can tackle it there.

**Pull request closed without merging**
