### PR TITLE
Allow to set sampling interval for profiling

### PR DESCRIPTION
**Pull request by drogus**
This PR is not complete yet (no specs etc), but I wanted to create a draft for a discussion. I wanted to play with sampling interval (which currently is set to 10ms), but at the moment the only way to do that is to change the hardcoded value. This PR adds it as an option in configurator. If that looks good I'll gladly prepare the PR to be merged.

### CODE REVIEW

**Comment by ivoanjo** [comment]
Hey @drogus, thanks for reaching out!

I'm curious, could you expand a bit on your use case here? Were you thinking of using this to make the profiler sample faster than the current hardcoded values, or slower?

One important note about the actual sampling rate you'll get when profiler is working is that there's actually two numbers that factor into it, not just one: [`DEFAULT_MAX_TIME_USAGE_PCT` and `MIN_INTERVAL`](https://github.com/DataDog/dd-trace-rb/blob/b20dc3b476754949b5de8c93715a661226206b8e/lib/ddtrace/profiling/collectors/stack.rb#L18-L19). `DEFAULT_MAX_TIME_USAGE_PCT` ensures that profiler should spend at most N% of wall-clock time working, and `MIN_INTERVAL` controls the lower bound on how often profiler samples.

This is why I'm curious about your use case, as the mechanism described above means there's no actual fixed sampling interval right now 😄

**Comment by drogus** [comment]
hi @ivoanjo!

In short - I was hoping to get more samples. I haven't been using the profiler too much yet, so I might be misunderstanding something, but it seems to me that most of the time I'm not getting enough insight into what's happening. I haven't noticed the max usage time before, though. That's a good guard, but I would probably want to play with it too. In any case I was hoping that if I set minimum sampling interval to a lower value like 5ms (or even 1ms?) I woudl get a bit more detailed results from the profiler.

**Comment by ivoanjo** [comment]
>  it seems to me that most of the time I'm not getting enough insight into what's happening

Thanks for sharing! When you mention this -- what view are you looking at? Is it the aggregation view, individual profiles, or viewing the "Code Hotspots" for a given traced request?

Making the profiler go faster is doable, but it's not something we were considering yet, as it can have a big impact on the overhead of an application. The current defaults and limits were tested to provide very low overheads and thus not impact production workloads.

Did you intend to use this setting for a production application, or was it for use in a testing environment?

**Comment by drogus** [comment]
Thanks for the additional context. I assumed that you were testing this stuff to not impact the application, but in a way I wanted to test it myself too, mainly to see if we can go a bit further on our particular setup, cause maybe it will differ from what you saw on your testing boxes.

Regarding lack of insight it's mostly about hotspots for traces. It might be that I haven't looked at enough examples, but I think that with 10ms frequency it's hard to really find hotspots.

And with the question about the intended usage. I wouldn't probably want to set it very low on production, but it would be nice to allow to change it for testing envs or even locally. Like, sometimes doing a quick check on a testing environment might be quicker than setting up data and all the other stuff locally.

**Comment by ivoanjo** [comment]
👍  got it. Let me get back to you on this matter, I'll bring it up with the rest of the team and see what we can do.

**Comment by ivoanjo** [comment]
Thanks for the patience! I've discussed it with the team and adding this option under a new "experimental" section seems reasonable.

@drogus are you still interested in contributing it?

As we were discussing above, I believe the changes needed here are:
1. Update the behavior of [`compute_wait_time`](https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/profiling/collectors/stack.rb#L173-L184)
2. Increase [`max_events`](https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/configuration/settings.rb#L162) when this option is set. Each "event" is individual thread stack trace, so the default of 32k will not be enough if the sampling rate is too high.

**Comment by drogus** [comment]
I'm sorry for a very late response! Yes, I'm interested in implementing this (unless you want it done fast and then maybe it's better if DD's team works on it?). Thanks for additional pointers, if I have any questions about this, I'll ask here.

**Comment by ivoanjo** [comment]
> I'm sorry for a very late response! Yes, I'm interested in implementing this (unless you want it done fast and then maybe it's better if DD's team works on it?). Thanks for additional pointers, if I have any questions about this, I'll ask here.

We'd love the contribution!

On our side, we're thinking about alternative approaches to sampling that would have less overhead (and thus allow us to ship with a higher default sampling rate) but that's definitely a bit far out, and I don't think both approaches would conflict 😄

**Comment by drogus** [comment]
@ivoanjo can you shed some light on your plans? I know you mentioned it's far out, so I'm not expecting any ETAs or whatever, just wondering about direction. eBPF? lower level sampling (like a native extension)? some other tracing options?

**Comment by ivoanjo** [comment]
We're very early in that effort, and we're still evaluating our options -- there's quite a bit of prior art in the Ruby community for the different approaches. All of them have trade-offs -- Linux-only, needing special permissions/extra setup in the OS, MRI-specific, no support for older Rubies, etc -- and so I think that the current approach will live for quite some time, possibly even as a fallback for setups where the fancier sampling may not work.

**Pull request closed without merging**
