### PR TITLE
Add note about `Datadog.configure` requiring block in 1.x to Upgrade Guide

### PR DESCRIPTION
**Pull request by ivoanjo**
Spotted this change when working with @lloeki on validating 1.0.0.beta2.

### CODE REVIEW

**Review by lloeki — APPROVED** [review]
LGTM

**Review by delner — CHANGES_REQUESTED** [review]
I don't really see this particular change as constructive or useful. It calls out a weird usage that was employed as a hack as if it's meant to be used this way.

I wouldn't recommend this. If the hack was predicated by some flaw, it would be better to address that flaw.

**Comment by ivoanjo** [comment]
@delner Since this is something that changed (and even bit us!) it seems nice to have it documented as a change in the "Breaking Changes" section -- it is an actual breaking change in the public API.

But I do agree that by itself, calling `Datadog.configure` shouldn't be useful or needed. So what're your thoughts on instead of suggesting:

> Use `Datadog.configure { }` instead.

we suggest:

> Remove usages of `Datadog.configure` without a block.

**Comment by ivoanjo** [comment]
Updated PR with the advice to remove such uses.

**Review by marcotc — APPROVED** [review]
I've used this pattern before, specially when trying to run the host application test with `ddtrace` enabled.

**Comment by ivoanjo** [comment]
I spoke with David a week back and he was happy with the alternative advice; merging this in.

**Pull request merged**
