### PR TITLE
Namespacing: Datadog::Tracing::Contrib

### PR DESCRIPTION
**Pull request by delner**
This pull request moves `Datadog::Contrib` to `Datadog::Tracing::Contrib`.

### CODE REVIEW

**Review by ivoanjo — COMMENTED** [review]
Arfffff this PR kinda breaks GitHub for me. I can barely type comments or scroll :/ (had to write this in sublime and copy/paste)

Part of the problem is that the three things being done for most (all?) files are:

* moving the file
* adding the tracing module
* changing the indentation

and of these, changing the indentation really breaks git's detection of "oh actually this is just the same".

To make this PR more readable, I suggest breaking it into two PRs (or at least two commits):

1. Move the file + add the tracing module without reeindenting the files

e.g. instead of

```ruby
module Datadog
  module Tracing
    module Contrib
```

use

```ruby
module Datadog
module Tracing
  module Contrib
```

This will allow us to review a PR that should contain only file moves + adds 2 lines to each file.

2. Fix the indentation in a separate PR. This allows us to review a PR where we can disable whitespace changes and confirm that nothing else changed trivially.

**Comment by delner** [comment]
@ivoanjo The indentation idea sounds good, but there's no way to un-indent/re-indent en masse (that I know of.) A search and replace only works on those `module` definitions (not the rest of the body of the file), and I don't know of another automated way to do this. I nearly injured my wrist from the repetition doing the indentation as was :sob:

All the same, I will see if there's a way to break up the commit somehow.

**Review by marcotc — APPROVED** [review]
This PR is surprisingly "boring", many so changes, but they are all the same. 🦭 

The worst part is that my PC does this when reviewing the PR via GitHub's interface: https://www.youtube.com/watch?v=dCO89JvatxQ

**Review by ivoanjo — APPROVED** [review]
LGTM :+1:

Thanks for splitting the commits -- it made reviewing totally doable. Now if you'll excuse me, I have a scroll wheel to replace...

**Review by lloeki — APPROVED** [review]

**Comment by delner** [comment]
@marcotc I could always make it more exciting for you :smile:

**Pull request merged**
