### PR TITLE
Upload coverage report to Codecov

### PR DESCRIPTION
**Pull request by brettlangdon**
Will install and upload final coverage report to Codecov in CI (while still generating the html formatted report)

### CODE REVIEW

**Review by ericmustin — APPROVED** [review]

**Comment by marcotc** [comment]
Are the reports correct? I tried it and it seems like it doesn't merge the results properly (the results from the `coverage` CI step are different from codecov UI).

Here's a branch with my attempt a few weeks ago: https://github.com/DataDog/dd-trace-rb/compare/ci/ship-coverage-to-codecov

**Comment by brettlangdon** [comment]
It looks the same to me? I didn't do a file-by-file comparison, but the resulting percentage is the same. It is also the same `SimpleCov.collate` step, so the reports should be the same (I hope).

https://app.codecov.io/gh/DataDog/dd-trace-rb/branch/brettlangdon%2Fcodecov
https://102258-66497320-gh.circle-artifacts.com/0/coverage/index.html#_AllFiles

**Comment by marcotc** [comment]
I see you only install `codecov` on the last step, and thus submits only the final result, so the results are the same. I think that makes sense.
I was submitting results on every single job, and codecov wasn't merging it properly on their side.

**Review by marcotc — APPROVED** [review]

**Comment by brettlangdon** [comment]
Ah, yeah. We are having some issues with that in Python as well. It takes a _long_ time to merge the results.

**Pull request merged**
