### PR TITLE
Temporarily lock Rake version for Appraisal

### PR DESCRIPTION
**Pull request by marcotc**
Appraisal missed a `require 'set'` statement in their code, but `rake` was bailing them out.

Rake released a new version today (`13.0.4`) that moves the `require 'set'` to a different location, thus appraisal broke.

A fix has been submitted to `appraisal`: https://github.com/thoughtbot/appraisal/pull/184

The relevant change is in `Gemfile`. Everything else is appraisal updates.

### CODE REVIEW

**Review by ericmustin — COMMENTED** [review]
👍  lgtm once gemfiles update rake task completes

**Comment by marcotc** [comment]
Feel free to merge this PR if you need it to unblock your work.

**Review by ericmustin — APPROVED** [review]

**Comment by ivoanjo** [comment]
Looks like a new release of `racecar` broke 2.4. I'll ping upstream about it, possibly ask them to include a minimum ruby version on the gemfile.

**Comment by ivoanjo** [comment]
Reported upstream: https://github.com/zendesk/racecar/issues/252 . I suggested that it'd be nice if they yanked 2.3.0, but we may want to add a temporary restriction to our `Appraisals` file to use `racecar` `< 2.3` on Ruby < 2.5 to unblock our CI.

Ah, the joys of legacy Ruby support.

**Pull request merged**
