### PR TITLE
fixes #630 potential performance hit logging cache key

### LINKED ISSUE #630: cache key logging can have performance side effects
I'm looking at behaviour of rails caching when passing a collection (e.g. AR relation), and even though there's already a [problem related to this](https://github.com/rails/rails/pull/29092#issuecomment-437572543) with rails, if/when this problem is fixed, I anticipate a similar problem with the DD tracer at https://github.com/DataDog/dd-trace-rb/blob/282855235bd83a5e0df25bd5268bf7524ddd6ce1/lib/ddtrace/contrib/rails/active_support.rb#L53

I tested it with the rails issue patched, and observed that logging the cache key on this line can have a performance side effect of evaluating the key, causing a potentially heavy DB query.

I know this sounds a bit vague, but as a crude example, if my cache key is `Project.all`, rails would typically evaluate it into a cache key using an efficient DB query (`SELECT COUNT(*) AS "size", MAX("projectsl"."updated_at") AS timestamp FROM "projects"`), but then when the same key is logged by the Datadog agent, it would evaluate `Project.all` and generate a much heavier query (`SELECT projects".* from "projects"`).

I'm not very familiar with the dd-tracer, but just observed this when experimenting with this, so I thought I'd report this. Perhaps there's a way to get the key from rails after it's been "expanded" into a string? or use a helper to log the key in a more efficient form? e.g. `ActiveSupport::Cache.expand_cache_key(payload.fetch(:key))` ?

### PR DESCRIPTION
**Pull request by gingerlime**
* using ActiveSupport::Cache.expand_cache_key which is also
  used by Rails to expand the cache key without enumerating
  relations

### CODE REVIEW

**Comment by gingerlime** [comment]
On a side note, it seems to me like the ddtracer patches ActiveSupport in order to trace cache reads, writes, etc. But wouldn't be more elegant to use the built-in rails instrumentation for that? https://edgeguides.rubyonrails.org/active_support_instrumentation.html#active-support

**Comment by delner** [comment]
@gingerlime On the tests, you almost had it right with `appraisal rails5-postgres-redis`. The Rails tests run under specific appraisals for each version, so you just have to choose the right one from the Appraisals file for the version of Ruby that you're using. They should work if you pair Ruby version to appraisal correctly. You could also look at our CI there for an example of the commands that it runs (should be identical to what you run in the container.)

**Comment by gingerlime** [comment]
@delner I added a couple of simple tests, and CI looks green (apart from what looks like an unrelated failure).

Regardless, I'm curious to hear your thoughts about https://github.com/DataDog/dd-trace-rb/pull/635#issuecomment-440951424 ...

**Comment by delner** [comment]
@gingerlime Honest answer as to why we don't use the ActiveSupport hooks: I don't know. It might be because we support Rails versions as old as 3.0 and this doesn't exist in those older versions, or that we simply didn't see that event when the integration was created.

If a PR was created to use that instrumentation hook, and it was implemented in a way such that it passes our test suite, I would seriously consider merging it. I don't know if we'd get around to writing such a refactor soon otherwise; we'd likely add it to the backlog instead.

**Pull request merged**
