### PR TITLE
DOCS-4628 Ports must match agent config

### PR DESCRIPTION
**Pull request by kayayarai**
**What does this PR do?**
Updates doc to be explicit that library config of ports must match Agent config

**Motivation**
DOCS-4628, customer confusion

**Additional Notes**
This also needs to be merged to `release` branch to be picked up in the docs site

**How to test the change?**

### CODE REVIEW

**Review by ivoanjo — APPROVED** [review]
:+1: LGTM

It occurs to me that these docs are slightly incomplete, since the host and port are where data in general will be sent (trace data + profiling data + telemetry data), but I can submit a follow-up PR to fix that.

**Comment by ivoanjo** [comment]
Merging away, thanks @kayayarai :)

**Comment by ivoanjo** [comment]
(There's a bunch of CI things complaining but they are unrelated to this docs-only change)

**Comment by ericmustin** [comment]
idk why i'm getting circleci build fail notifications from this repo still but was happy to see @kayayarai with the contribution! yay! (hope all y'all are well!)

**Comment by kayayarai** [comment]
@ericmustin !!!!! <3

**Comment by ivoanjo** [comment]
@ericmustin Ahaha you're always welcome to come by, circleci notifications or not ;)

**Pull request merged**
