### PR TITLE
Update docker image usage

### PR DESCRIPTION
**Pull request by lloeki**
**What does this PR do?**

Make use of the new image versions.

**Motivation:**

The above.

**Additional Notes:**

On `1.x-stable`, Ruby and JRuby image building should be restricted to those that are not on `master`.

But really, base images should come from https://github.com/DataDog/images-rb instead.

**How to test the change?**

CI should pass.

Unsure? Have a question? Request a review!

### CODE REVIEW

**Comment by lloeki** [comment]
Looks like 3.1, 3.2, and 3.3 are not happy about FFI:

```
An error occurred while loading ./spec/datadog/tracing/contrib/ethon/typhoeus_integration_spec.rb. - Did you mean?
                    rspec ./spec/datadog/tracing/contrib/ethon/integration_test_spec.rb
                    rspec ./spec/datadog/tracing/contrib/ethon/integration_spec.rb
                    rspec ./spec/datadog/tracing/contrib/ethon/integration_context.rb

Failure/Error: require 'ethon'

LoadError:
  libffi.so.7: cannot open shared object file: No such file or directory - /usr/local/bundle/gems/ffi-1.16.3/lib/ffi_c.so
```
```  
# --- Caused by: ---
# LoadError:
#   cannot load such file -- 3.2/ffi_c
#   /usr/local/bundle/gems/ffi-1.16.3/lib/ffi.rb:3:in `require'
```

**Comment by ivoanjo** [comment]
> Looks like 3.1, 3.2, and 3.3 are not happy about FFI:

I think that's CI caching -- it's reusing the installed gems from the older debian version.

**Comment by lloeki** [comment]
Bumping `binary_version` to create another cache worked for CRuby but JRuby still presents crashes.

**Review by marcotc — APPROVED** [review]

**Comment by ivoanjo** [comment]
This is outdated, as we're now sourcing our images from https://github.com/DataDog/images-rb (I believe based on @lloeki's initial work still -- thanks for that). Going to go ahead and close this one.

**Pull request closed without merging**
