### PR TITLE
Adds support for Sequel ruby gem.

### PR DESCRIPTION
**Pull request by randy-girard**
Adds sequel (https://github.com/jeremyevans/sequel) support.

### CODE REVIEW

**Comment by randy-girard** [comment]
Please suggest what else should be updated, or any suggestions to this. 

image

image

image

**Comment by ufoot** [comment]
Oh nice. Will go through it, for sure. Thanks very much for posting this!

**Comment by ufoot** [comment]
Hi @randy-girard I created #171 which basically takes your work as a start (and thanks, good PR really, tests & all, nice) and enhances it a little bit. I mostly worked on refining the resources so that we get real clues on what is executed. Your patch had the stats working well but span details needed some more work. Could you try the code in PR #171 and confirm it works on your environment? Thanks again for your work.

**Comment by randy-girard** [comment]
Hey, sorry I haven't replied. We have been busy with some unexpected issues over the last few weeks that have taken we away from this focus. I'm also leaving for a vacation today and wont be back until after next week. I can give it a test when I get back, if thats not a problem. It looks to good though from what I can tell.

**Comment by irabinovitch** [comment]
@randy-girard Did you have a chance to check out #171 ? Would it make sense to close this PR in favor of that one.

**Comment by randy-girard** [comment]
So sorry, forgot about this. I'll go take a look and close this.

**Comment by palazzem** [comment]
Want to notify everyone (particularly @randy-girard ) that the Sequel PR has been reviewed and reworked to be part of our 0.13 release. Here more detail: https://github.com/DataDog/dd-trace-rb/pull/171

Thanks a lot @randy-girard for your contribution!

**Pull request closed without merging**
