### PR TITLE
Rails subservice service_name

### PR DESCRIPTION
**Pull request by dudo**
Adds the rest of the rails integrations as overridable

- mailer_service
- cable_service

### CODE REVIEW

**Review by dpep — APPROVED** [review]
lgtm

**Review by theaxel — APPROVED** [review]

**Comment by marcotc** [comment]
@dudo thank you for this PR.

This would 100% be the right change a week ago, but we've finally started making some good progress towards improving the service naming conventions in `ddtrace`.

The end goal is to not have users worry about configuring each service name explicit, and let the backend distinguish between different internal application components (e.g. Rails cache, ActionCable) without manual service name configuration. The goal is to only require a single `DD_SERVICE`, and let the rest be automatically handled (without any loss of visibility or grouping).

You can see [in this open PR](https://github.com/DataDog/dd-trace-rb/pull/1800/files#diff-c3078b75a8af1db0f383fcb079f73e4fe5d768c40488de19a645418229382da1) that we are actually removing the Rails framework options for configuration "sub-components" components directly in `c.use :rails`. This Rails framework sub-component service name configuration has been a source of many bugs in the past, and not something we will support in the long term.

To make it clear, we are **not** removing the ability to configure the service name for each Rails sub-component: e.g. `c.use :active_record, service_name: 'my-service'` will still work, but not `c.use :rails, database_service: 'my-service'`. Like I mentioned, the main reason being is causes confusing and bugs when mixing `c.use :rails` and `c.use :active_record`, and our desire to remove the necessity to configure service names ahead of time in application code.

**Comment by dudo** [comment]
@marcotc That aligns with how I want to use this, I believe. In the meantime, would you suggest we remove the `rails` integration, and just enable each sub-component individually?

**Comment by marcotc** [comment]
> @marcotc That aligns with how I want to use this, I believe. In the meantime, would you suggest we remove the `rails` integration, and just enable each sub-component individually?

Enabling each component is tricky, as you now have to know which rails sub-components exist and which ones are supported by `ddtrace`.

I recommend leaving `c.use :rails`, but configure specific sub-component service names separately:
```ruby
c.use :rails
c.use :active_record, service_name: 'my-service'
```

This will make sure you don't need any changes in our coming releases, and also ensures that you can simply remove the `c.use :active_record, service_name: 'my-service'` line when we finish our complete work around service naming (leaving only `c.use :rails` with no settings).

**Pull request closed without merging**
