### PR TITLE
Initial integration of Roda.

### PR DESCRIPTION
**Pull request by randy-girard**
I have a need to instrument Roda framework, so I took at stab at it locally and just ported it into the Gem. Feel free to rip it apart and fix it up for release :)

### CODE REVIEW

**Comment by delner** [comment]
@randy-girard Thanks for the contribution! This is a good first step; I'll try to get this a thorough review in the near future. :)

In the mean time, I would suggest adding some RSpec tests. Particularly it would be good to add some integration tests where we can demonstrate the instrumentation produces spans with proper attributes, especially around any special cases or edge cases where you expect different behavior.

You should be able to use many of the other integrations as examples of how to do this. Also be sure to add the appropriate commands to the Rakefile so these new tests run in CircleCI!

**Comment by mbarany** [comment]
👋  Hey, just checking in to see if there are plans to get this merged in anytime soon. We have a Roda app that could benefit from an integration.

**Comment by marcotc** [comment]
👋 @randy-girard & @mbarany, I'll schedule a review and follow up to this for our coming sprint. I'll let you know when we have an update.

**Comment by radek2r** [comment]
@marcotc Is there any update?

**Comment by ivoanjo** [comment]
It took a while, but last year we finally got a Roda integration going in https://github.com/DataDog/dd-trace-rb/pull/2368 !

I'm going to go ahead and close this PR. Thanks Randy for getting the ball rolling, although it took a...bit...longer :sweat_smile: 

Do feel free to reach out if we can help further on this issue or in others :)

**Pull request closed without merging**
