### PR TITLE
[faraday] Add hostname to faraday annotation

### PR DESCRIPTION
**Pull request by tinchi**
Faraday integration is not very informative right now:
screen shot 2018-03-29 at 5 29 07 pm
So i added hostname to the resource name

### CODE REVIEW

**Comment by delner** [comment]
Thanks for the contribution @tinchi!  I think this could be a good change, since you're right... `GET` isn't very useful in itself. The technical implementation details seem fine. I also think it might be worth considering how this interplays with the UI and the intent there.

The `resource` field typically represents a group of traces, each of which you might consider an instance of the same "thing". So what's the right granularity here for a Faraday trace? `GET` seems too broad. Adding the host seems to be better. Should it also include the path or query string too?

Without trying to expand the scope on this PR too much, I'm going to think on this a bit, so we know how this fits into making Faraday better.

**Comment by tinchi** [comment]
@delner by using only hostname i would get a better overview of how particular host behaves in terms of latency and error rate. 
screen shot 2018-04-02 at 11 07 50 am
ideally i would want it to look like this: 
screen shot 2018-04-02 at 11 18 41 am
but don't think its possible to implement to implement this format

**Comment by delner** [comment]
@tinchi Is that bottom screenshot something you photoshopped? (For sake of example?)

**Comment by tinchi** [comment]
@delner yeah just few tweaks in the chrome's dev console

**Comment by delner** [comment]
@tinchi Could we rebase this on `0.13-dev`? Looks like there's a merge conflict since we migrated the Faraday minitests to RSpec.

**Comment by tinchi** [comment]
@delner gonna do it shortly

**Comment by delner** [comment]
This seems related to #277 since they are both concerned with assigning better `resource` names to traces of HTTP requests. We'll likely want to make the behavior consistent across each of these HTTP clients, so we should probably address what that looks like there before we move ahead with this change. This behavior is still currently up for discussion.

**Pull request closed without merging**
