### PR TITLE
Background job custom error handlers

### PR DESCRIPTION
**Pull request by norbertnytko**
**Goal**
Allow passing custom error handler for background job gems. Useful to retry jobs for known transient errors without reporting errors to Datadog.

Example usage:
```ruby
TRANSIENT_ERRORS = [SomeTransientError]
# This can be any callable object, provided `span` and `error` as arguments.
custom_error_handler = proc { |span, error| span.set_tag('error', true) unless TRANSIENT_ERRORS.include?(error.class) }

Datadog.configure do |c| 
  c.use :sidekiq, {
    error_handler: custom_error_handler
  }
end
```

### CODE REVIEW

**Comment by ericmustin** [comment]
@norbertnytko Thanks for the contribution. I've given this a quick pass, this looks like great work and very thorough. Would you mind describing your use case here a bit more? My understanding is, there are some background jobs that throw errors which you may not want marked as an `error` on the trace / trace related metrics / etc ? Or, you want to perform some arbitrary logic on them to determine if they're an error? Is this broadly correct? Are there other use cases here I am missing, if so would you mind explaining a bit so that we're aligned?

I think what you're proposing is reasonable, and recently we've seen a few use cases where users would like to pass in a custom `error_handler` for various integration, similar to [what exists for some http clients currently](https://github.com/DataDog/dd-trace-rb/blob/5cc47254458f7f3cc303cb59078a0d435fb894e0/docs/GettingStarted.md#excon). So I think this is worth having as a feature. If anything I think it may make sense to generalize this for all integrations, but I don't want to let perfect get in the way of good, so i'd be happy to see this accepted in it's current scope (i do still need to review more thoroughly) and set aside time to build on it.

**Review by ericmustin — CHANGES_REQUESTED** [review]
- One small nit is that we'll need to update the config instructions in `GettingStarted.md` to reflect the new options for each integration.

**Review by ericmustin — APPROVED** [review]
Nice work here. lgtm, approving. I'd like to have one of the other maintainers take a look here as well so going to wait to merge this in until next week when they return from PTO, if that's ok.

Some good next steps here for future work:

- validation around the Proc that gets passed in.
  - we'd probably want to do this within the `tracer.trace` [rescue block](https://github.com/DataDog/dd-trace-rb/blob/a2213363dbae8f696b7c33cb90b4285fa56e1ec4/lib/ddtrace/tracer.rb#L291) and log a debug or warn msg if the arg doesn't respond to `call`, but don't think this is blocking at the moment since we don't do vallidation around the `tracer.trace` `on_error` arg currently.
- extending `error_handler` to other integrations beside just workers.

**Review by marcotc — APPROVED** [review]
Thank you again, @norbertnytko! Looks :shipit: to me.

**Pull request merged**
