### PR TITLE
[NO-TICKET] Upgrade to libdatadog 14.0

### PR DESCRIPTION
**Pull request by ivoanjo**
**What does this PR do?**

This PR upgrades the libdatadog dependency to the latest 14.0 release.

It also updates our API usage to match some 13.1 -> 14.0 changes.

**Motivation:**

The libdatadog 14.0 release includes a number of improvements to the crashtracking implementation, and we want to pick them up.

**Change log entry**
Upgraded libdatadog dependency to version 14.0

**Additional Notes:**

As a first pass, I've disabled the creation and use of the alt stack, to match our existing setup.

I did not yet experiment with `use_alt_stack = true`.

**How to test the change?**

Existing test coverage should be enough to cover our libdatadog API usage.

### CODE REVIEW

**Review by Strech — APPROVED** [review]
I hope no things forgotten to be set 🙈

**Comment by ivoanjo** [comment]
> I hope no things forgotten to be set 🙈

I've dropped a note to @sanchda which has been doing a lot of working on libdatadog crashtracking so he can do a quick pass on that part as well :)

**Review by sanchda — APPROVED** [review]
The only issue, which we discussed offline, is whether or not it's appropriate to use the altstack even if it isn't created.  I trust @ivoanjo to make whatever decision is appropriate for the runtime, so approving.

👍 🚀 🚀

**Review by p-datadog — APPROVED** [review]

**Review by p-datadog — APPROVED** [review]

**Comment by ivoanjo** [comment]
I spent some time looking into `use_alt_stack` setting and I think there's a bug in libdatadog and that setting doesn't seem to be doing anything at this point.

Since the Ruby VM itself sets an altstack, this leaves us:

* In libdatadog 13.1, the crashtracker code always used the altstack (e.g. equivalent of `use_alt_stack` was hardcoded to `true`) => in libdatadog 13.1 we used the Ruby altstack
* In libdatadog 14.0, the crashtracker code chooses to use the altstack based on the value of `create_alt_stack` => libdatadog 14.0 we can't use the Ruby altstack

Since the crashtracker is currently off by default, I don't think this should be a blocker for upgrading to libdatadog 14.

In preparation for `use_alt_stack` to get fixed in a future libdatadog release, I'll push a commit to change it to true, although, again, right now it's a no-op.

**Review by AlexJF — APPROVED** [review]

**Pull request merged**
